# Generated by Django 2.1.3 on 2018-11-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181104_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langauage',
            new_name='language',
        ),
    ]
